"""
🧠 LLM Interpreter — EXPLAINS signals, NEVER generates them
================================================================
The LLM's role is strictly:
  1. Interpret the signal in natural language
  2. Provide context and narrative
  3. Answer "Why does this trade make sense?"
  4. Translate for non-technical users

The signal_engine generates ALL signals deterministically.
The LLM adds the human-readable explanation layer on top.
"""

import os
import json
import logging

logger = logging.getLogger("trade_bot.llm_interpreter")


def interpret_signal(signal_data: dict) -> str:
    """
    Take a structured signal from signal_engine and produce
    a human-readable interpretation. Uses HF Inference API.
    Falls back to template-based interpretation if LLM unavailable.
    """
    # Always try LLM first, fallback to template
    try:
        hf_token = os.environ.get("HF_TOKEN", "")
        if hf_token:
            return _llm_interpret(signal_data, hf_token)
    except Exception as e:
        logger.warning(f"LLM interpretation failed: {e}")
    
    return _template_interpret(signal_data)


def _llm_interpret(signal_data: dict, token: str) -> str:
    """Use HF Inference API to interpret the signal."""
    from huggingface_hub import InferenceClient
    
    model_id = os.environ.get("MODEL_ID", "Qwen/Qwen2.5-72B-Instruct")
    client = InferenceClient(model=model_id, token=token)
    
    prompt = f"""You are a financial analyst explaining a trading signal to a client.
The signal was generated by a deterministic rule-based system (NOT by you).
Your job is ONLY to explain it clearly. Do NOT change or override the signal.

Signal data:
{json.dumps(signal_data, indent=2, default=str)}

Write a concise 3-5 sentence analysis in Turkish that:
1. States the signal clearly
2. Explains WHY the indicators support this view
3. Mentions the key risk factors
4. Answers "Bu trade neden mantıklı?" (or why it's best to HOLD)

Be direct, data-driven, no fluff. Reference actual indicator values."""

    response = client.text_generation(
        prompt,
        max_new_tokens=300,
        temperature=0.3,
    )
    return response


def _template_interpret(signal_data: dict) -> str:
    """Template-based interpretation when LLM is unavailable."""
    ticker = signal_data.get("ticker", "?")
    signal = signal_data.get("signal", "HOLD")
    confidence = signal_data.get("confidence", 0)
    risk = signal_data.get("risk", "medium")
    reasons = signal_data.get("reasons", [])
    trade = signal_data.get("trade", {})
    indicators = signal_data.get("indicators", {})
    
    rsi = indicators.get("rsi", {}).get("value", "?")
    sma_detail = indicators.get("sma_crossover", {}).get("detail", "")
    vol_regime = indicators.get("volatility", {}).get("regime", "?")
    
    signal_tr = {
        "STRONG_BUY": "GÜÇLÜ AL", "BUY": "AL", "HOLD": "BEKLE",
        "SELL": "SAT", "STRONG_SELL": "GÜÇLÜ SAT"
    }.get(signal, signal)
    
    lines = [
        f"**{ticker}** için sinyal: **{signal_tr}** (Güven: %{confidence})",
        "",
    ]
    
    if reasons:
        lines.append("**Nedenler:**")
        for r in reasons[:4]:
            lines.append(f"• {r}")
        lines.append("")
    
    if signal in ("BUY", "STRONG_BUY") and trade.get("entry_price"):
        lines.append(f"**Trade:** Giriş ${trade['entry_price']}, SL ${trade.get('stop_loss', '?')}, "
                     f"TP ${trade.get('take_profit', '?')}, R/R {trade.get('risk_reward', '?')}")
    elif signal in ("SELL", "STRONG_SELL"):
        lines.append(f"**Uyarı:** Satış baskısı altında. Pozisyon azaltma/hedge düşünülmeli.")
    else:
        lines.append(f"**Önerı:** Net sinyal yok. Piyasanın yönünü beklemek daha sağlıklı.")
    
    lines.append(f"\n*Risk seviyesi: {risk} | Volatilite: {vol_regime} | RSI: {rsi}*")
    
    return "\n".join(lines)


def chat_with_context(message: str, signal_context: dict = None) -> str:
    """
    Chat function for the advisor tab. LLM answers questions
    about the market/signal using the signal data as context.
    """
    try:
        hf_token = os.environ.get("HF_TOKEN", "")
        if not hf_token:
            return "⚠️ HF_TOKEN gerekli. Chat fonksiyonu için environment variable olarak ekleyin."
        
        from huggingface_hub import InferenceClient
        
        model_id = os.environ.get("MODEL_ID", "Qwen/Qwen2.5-72B-Instruct")
        client = InferenceClient(model=model_id, token=token)
        
        context = ""
        if signal_context:
            context = f"\nCurrent signal data:\n{json.dumps(signal_context, indent=2, default=str)}\n"
        
        prompt = f"""You are a trading advisor assistant. You explain trading signals and market analysis.
Signals are generated by a rule-based system, not by you.
Answer in the same language as the user's question (Turkish or English).
Be concise and data-driven.{context}

User: {message}
Assistant:"""
        
        response = client.text_generation(prompt, max_new_tokens=500, temperature=0.5)
        return response
    except Exception as e:
        return f"⚠️ Chat hatası: {e}\n\nLLM olmadan da sinyal motoru çalışır — 📊 Analiz ve 📊 Backtest tablarını kullanın."
